# Generated by Django 2.2.5 on 2021-01-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210107_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenitie'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facilite'},
        ),
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name': 'House Rule'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'RoomType'},
        ),
    ]
